### ISSUE TITLE
Proposal: Move to https://github.com/openSUSE

### ISSUE THREAD

**Issue by okurz** [openSUSE/Mojo-IOLoop-ReadWriteProcess#34]
We see this project being actively used by e.g. the [os-autoinst project](https://github.com/os-autoinst/os-autoinst) , there are packages within openSUSE and there is active review and contribution work by multiple contributors (and less the original author). I suggest to move the project to the openSUSE scope in github. If you agree then I suggest you (any owner of the project) transfer the ownership in the github settings. Someone in the openSUSE project (not sure if I can do this) should be able to accept the request.

**Comment by mudler** [comment]
I'd second this, but I'm not even in the openSUSE org, is there a way later to keep having permissions?

**Comment by okurz** [comment]
> I'd second this, but I'm not even in the openSUSE org, is there a way later to keep having permissions?

well, two ways. Either ask to be added to the org or the new owner will make sure that will keep maintainership permissions. I will ask in IRC if someone in the openSUSE org can do that for us.

**Comment by okurz** [comment]
ok, so the suggested way was that you request the ownership transfer over the "transfer ownership" tab of the project and then who accepts that should also add you and us accordingly in the new project. Can you do that?

**Comment by mudler** [comment]
I get the fol

> ok, so the suggested way was that you request the ownership transfer over the "transfer ownership" tab of the project and then who accepts that should also add you and us accordingly in the new project. Can you do that?

Just tried that, Settings -> Transfer Ownership -> added openSUSE there

I get the following error "You don't have the permissions to create public repositories on openSUSE"

**Comment by okurz** [comment]
ah, geez. So that needs to be done first.

**Comment by okurz** [comment]
if you like we can also go with os-autoinst. For that you could add me as owner or maintainer here and I should be able to transfer

**Comment by mudler** [comment]
> ah, geez. So that needs to be done first.

Can't even join the chat, the element link stays at "Loading room preview".. is there anything I can do to help you with this?

**Comment by foursixnine** [comment]
> > ah, geez. So that needs to be done first.
> 
> Can't even join the chat, the element link stays at "Loading room preview".. is there anything I can do to help you with this?

Make me a repo mantainership, and I'll take care of the rest :)

**Comment by mudler** [comment]
> > > ah, geez. So that needs to be done first.
> > 
> > 
> > Can't even join the chat, the element link stays at "Loading room preview".. is there anything I can do to help you with this?
> 
> Make me a repo mantainership, and I'll take care of the rest :)

You have already full permissions, can't do more than that on github.

Where should I ask to get added to the openSUSE org?

**Comment by mudler** [comment]
for the moment, I'll send an invite to all of you until this is figured out

**Comment by Vogtinator** [comment]
> thx, that's kind of you. With push access we can merge pull requests but we can't transfer the project.

Looks like it. I don't see the "Settings" tab, where the "Transfer ownership" option would be.

I have access to create repos in openSUSE, but for some reason no permissions to change permissions in the created repository, so we probably need a org owner for this anyway.

**Comment by coolo** [comment]
@mudler needs to initiate it and then the owner of the given organization needs to approve

**Comment by coolo** [comment]
OK, I was wrong. So you need to have @Vogtinator as repo owner here and then @Vogtinator can initiate it. (https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository )

**Comment by Vogtinator** [comment]
> @kkaempf just invited me, repo has been moved :)

Welcome in the new location!

**Comment by okurz** [comment]
I suggest to

**Comment by okurz** [comment]
I suggest to also update references to the project before we close this, e.g. in README, source code references, OBS package, CPAN, etc.

**Comment by okurz** [comment]
@foursixnine can you update https://metacpan.org/pod/Mojo::IOLoop::ReadWriteProcess please?

**Comment by foursixnine** [comment]
@okurz waiting on https://github.com/openSUSE/Mojo-IOLoop-ReadWriteProcess/pull/33

**Comment by perlpunk** [comment]
I noticed that there is no link to the github repo on MetaCPAN, and the Issues link points to RT.
https://rt.cpan.org/Public/Dist/Display.html?Name=Mojo-IOLoop-ReadWriteProcess
Is anyone reading those?

See https://metacpan.org/release/TINITA/YAML-PP-0.030/source/META.yml#L142 for an example how to specify a repo and issue tracker.

**Comment by foursixnine** [comment]
> > See https://metacpan.org/release/TINITA/YAML-PP-0.030/source/META.yml#L142 for an example how to specify a repo and issue tracker.
> 
> ~And to be a little more precise, here the information would probably go into the `distmeta` section of `Build.PL`.~
> 
> Edit: Actually it should go into `minil.toml`. grin
> 
> ```
> [Metadata.resources]
> repository: https://github.com/openSUSE/Mojo-IOLoop-ReadWriteProcess
> ```

adding it

**Comment by foursixnine** [comment]
I'd say we have [CPAN](https://metacpan.org/release/SZARATE/Mojo-IOLoop-ReadWriteProcess-0.32) however, https://github.com/openSUSE/Mojo-IOLoop-ReadWriteProcess/pull/39 is still pending along with the version tag... which makes me believe that there will be  a 0.33.1 :)

**Comment by okurz** [comment]
I'd say that's enough then.

**Comment by kraih** [comment]
I think we still only have one person who can make CPAN releases (@foursixnine). One or two more with co-maint might be a good idea to improve the bus factor.
