### ISSUE TITLE
t/01_run.t, t/06_events.t use /usr/bin/true /usr/bin/false: not portable, should be /bin/true and /bin/false.

### ISSUE THREAD

**Issue by viy2** [openSUSE/Mojo-IOLoop-ReadWriteProcess#45]
t/01_run.t, t/06_events.t use /usr/bin/true /usr/bin/false.
those tests fail on more traditional Linux distributions that does not use /bin -> /usr/bin symlink.

use of /usr/bin/true /usr/bin/false is not portable, 
/bin/true and /bin/false should be used.

**Comment by cfconrad** [comment]
I take it, as I was the one how introduced it.

**Comment by cfconrad** [comment]
https://github.com/openSUSE/Mojo-IOLoop-ReadWriteProcess/pull/46 should address this issue!
